<a href="https://colab.research.google.com/github/sreejas7919-bit/DSA_6/blob/main/casestudy_PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CASE STUDY PANDAS**

1. Import pandas and numpy

In [1]:
import pandas as pd
import numpy as np

2) Load dataset using pd.read_csv()

In [6]:
df = pd.read_csv('/content/IMDB-Movie-Data.csv')
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

3. Display shape, head, column names, datatypes, missing values

In [49]:
print("Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
print(df.head())

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

Shape:
(1000, 16)

First 5 Rows:
   Rank              Movie_Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1     2               Prometheus  Adventure,Mystery,Sci-Fi
2     3                    Split           Horror,Thriller
3     4                     Sing   Animation,Comedy,Family
4     5            Suicide Squad  Action,Adventure,Fantasy

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn
1  Following clues to the origin of mankind, a te...          Ridley Scott
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4  A secret government agency recruits some of th...            David Ayer

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123

   Rating   Votes  Revenue (Millions)  Metascore  Number_of_Genres  \
0     8.1  757074              333.13       76.0                 3
1     7.0  485820              126.46       65.0                 3
2     7.3  157606              138.12       62.0                 2
3     7.2   60545              270.32       59.0                 3
4     6.2  393727              325.02       40.0                 3

   Profitability Rating_Category  Movie_Score
0       2.753140       Excellent       414.13
1       1.019839         Average       196.46
2       1.180513         Average       211.12
3       2.502963         Average       342.32
4       2.642439         Average       387.02

Column Names:
Index(['Rank', 'Movie_Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Number_of_Genres', 'Profitability', 'Rating_Category',
       'Movie_Score'],
      dtype='object')

Data Types:
Rank                    int64
Movie_Title            object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
Number_of_Genres        int64
Profitability         float64
Rating_Category        object
Movie_Score           float64
dtype: object

Missing Values:
Rank                  0
Movie_Title           0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
Number_of_Genres      0
Profitability         0
Rating_Category       0
Movie_Score           0
dtype: int64

4. Check and remove duplicates

In [10]:
print("Duplicate Rows:", df.duplicated().sum())
df = df.drop_duplicates()
print("After Removing Duplicates:", df.shape)

Duplicate Rows: 0
After Removing Duplicates: (1000, 12)

5. Rename column (Title → Movie_Title)

In [50]:
df.rename(columns={"Title":"Movie_Title"}, inplace=True)

print(df.columns)

Index(['Rank', 'Movie_Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Number_of_Genres', 'Profitability', 'Rating_Category',
       'Movie_Score'],
      dtype='object')

6)  Get unique genres

In [51]:
genres = set()

for genre in df["Genre"]:
    for g in genre.split(","):
        genres.add(g.strip())

print(genres)

{'Mystery', 'Western', 'War', 'Action', 'Biography', 'Sci-Fi', 'Sport', 'Musical', 'Animation', 'Adventure', 'History', 'Fantasy', 'Family', 'Drama', 'Crime', 'Horror', 'Romance', 'Comedy', 'Music', 'Thriller'}

7. Extract Number of Genres per Movie

In [52]:
df["Genre_Count"] = df["Genre"].apply(lambda x: len(x.split(",")))

print(df[["Movie_Title", "Genre_Count"]].head())

               Movie_Title  Genre_Count
0  Guardians of the Galaxy            3
1               Prometheus            3
2                    Split            2
3                     Sing            3
4            Suicide Squad            3

8)  Handle missing values in 'Revenue (Millions)' and 'Metascore

In [61]:
df["Revenue (Millions)"] = df["Revenue (Millions)"].fillna(
    df["Revenue (Millions)"].mean()
)

df["Metascore"] = df["Metascore"].fillna(
    df["Metascore"].median()
)

print("Revenue Missing Values:",
      df["Revenue (Millions)"].isnull().sum())

print("Metascore Missing Values:",
      df["Metascore"].isnull().sum())

Revenue Missing Values: 0
Metascore Missing Values: 0

In [53]:
df["Revenue (Millions)"].fillna(
    df["Revenue (Millions)"].mean(),
    inplace=True
)

df["Metascore"].fillna(
    df["Metascore"].mean(),
    inplace=True
)

print(df.isnull().sum())

Rank                  0
Movie_Title           0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
Number_of_Genres      0
Profitability         0
Rating_Category       0
Movie_Score           0
Genre_Count           0
dtype: int64

/tmp/ipykernel_592/1823353981.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Revenue (Millions)"].fillna(
/tmp/ipykernel_592/1823353981.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Metascore"].fillna(

9. Top 5 Movies by Rating

In [35]:
top5_movies = df.nlargest(5, "Rating")
print(top5_movies[["Movie_Title", "Rating"]])

         Movie_Title  Rating
54   The Dark Knight     9.0
80         Inception     8.8
117           Dangal     8.8
36      Interstellar     8.6
96     Kimi no na wa     8.6

10) Movies with highest/lowest revenue

In [57]:
highest = df.loc[df["Revenue (Millions)"].idxmax()]

lowest = df.loc[df["Revenue (Millions)"].idxmin()]

print("Highest Revenue Movie:")
print(highest["Movie_Title"])

print("\nLowest Revenue Movie:")
print(lowest["Movie_Title"])

Highest Revenue Movie:
Star Wars: Episode VII - The Force Awakens

Lowest Revenue Movie:
A Kind of Murder

11)  Avg. rating by Director

In [58]:
avg_rating = df.groupby("Director")["Rating"].mean()

print(avg_rating)

Director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             7.00
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.04
Zackary Adler          5.10
Name: Rating, Length: 644, dtype: float64

12) Movies per year

In [38]:
df["Year"].value_counts()

Year
2016    297
2015    127
2014     98
2013     91
2012     64
2011     63
2010     60
2007     53
2008     52
2009     51
2006     44
Name: count, dtype: int64

13) Movies with rating > 8 & revenue > 100M

In [59]:
result = df[
    (df["Rating"] > 8) &
    (df["Revenue (Millions)"] > 100)
]

print(result[["Movie_Title", "Rating", "Revenue (Millions)"]])

                                      Movie_Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

14) Group by Director: avg Rating, Revenue

In [41]:
df.groupby("Director").agg({
    "Rating":"mean",
    "Revenue (Millions)":"mean"
})

                     Rating  Revenue (Millions)
Director
Aamir Khan             8.50            1.200000
Abdellatif Kechiche    7.80            2.200000
Adam Leon              6.50           82.956376
Adam McKay             7.00          109.535000
Adam Shankman          6.30           78.665000
...                     ...                 ...
Xavier Dolan           7.55           43.223188
Yimou Zhang            6.10           45.130000
Yorgos Lanthimos       7.20            4.405000
Zack Snyder            7.04          195.148000
Zackary Adler          5.10            6.530000

[644 rows x 2 columns]

15) Group by Year: count, avg Rating

In [42]:
df.groupby("Year").agg({
    "Movie_Title":"count",
    "Rating":"mean"
})

      Movie_Title    Rating
Year
2006           44  7.125000
2007           53  7.133962
2008           52  6.784615
2009           51  6.960784
2010           60  6.826667
2011           63  6.838095
2012           64  6.925000
2013           91  6.812088
2014           98  6.837755
2015          127  6.602362
2016          297  6.436700

16) Create a new column Profitability:

   a) Revenue divided by Duration
   b) Find top 10 most profitable movies

In [46]:
df["Profitability"] = df["Revenue (Millions)"] / df["Runtime (Minutes)"]

print(df[["Movie_Title", "Profitability"]].head())

               Movie_Title  Profitability
0  Guardians of the Galaxy       2.753140
1               Prometheus       1.019839
2                    Split       1.180513
3                     Sing       2.502963
4            Suicide Squad       2.642439

17) Create a column that categorizes movies by rating:
a) Rating < 6: Poor
b) 6 ≤ Rating < 7.5: Average
c) Rating ≥ 7.5: Excellent

In [47]:
def category(rating):
    if rating < 6:
        return "Poor"
    elif rating < 7.5:
        return "Average"
    else:
        return "Excellent"

df["Rating_Category"] = df["Rating"].apply(category)

print(df[["Movie_Title", "Rating", "Rating_Category"]].head())

               Movie_Title  Rating Rating_Category
0  Guardians of the Galaxy     8.1       Excellent
1               Prometheus     7.0         Average
2                    Split     7.3         Average
3                     Sing     7.2         Average
4            Suicide Squad     6.2         Average

18) Create a custom function to score movies based on:
i)
Apply row['Rating'] * 10 + row['Revenue (Millions)'] as High score
Apply a function to dataset to assign the score

In [60]:
def movie_score(row):
    return row["Rating"] * 10 + row["Revenue (Millions)"]

df["Movie_Score"] = df.apply(movie_score, axis=1)

print(df[["Movie_Title", "Movie_Score"]].head())

               Movie_Title  Movie_Score
0  Guardians of the Galaxy       414.13
1               Prometheus       196.46
2                    Split       211.12
3                     Sing       342.32
4            Suicide Squad       387.02

**COMPLETE PANDAS CASE STUDY**