<a href="https://colab.research.google.com/github/sreejas7919-bit/DSA_6/blob/main/DataAcquisitionCasestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## ***dataAcquisitionCasestudy***

In [10]:
import pandas as pd
import json

## **PART A**

Task 1
Read the Population dataset from the CSV file.
Hint:
● Use the pandas library.
● Display the first five rows.
● Check the shape and data types.

## Read Population CSV

In [11]:
population = pd.read_csv("population.csv")

population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

## Read GDP Excel

In [12]:
gdp = pd.read_excel("gdp.xlsx")

gdp.head()

         Country       GDP
0  United States  30500000
1          China  19230000
2          India   4187000
3          Japan   4180000
4        Germany   4744000

## Read Internet Users JSON

In [13]:
with open("internet_users.json") as file:
    data = json.load(file)

internet_users = pd.DataFrame(data)

internet_users.head()

         country  internet_users
0  United States       312000000
1          China      1080000000
2          India       850000000
3          Japan       118000000
4        Germany        79000000

## Read Literacy XML

In [14]:
literacy_rate = pd.read_xml("literacy_rate.xml")

literacy_rate.head()

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

In [15]:
print(population.head())
print(gdp.head())
print(internet_users.head())
print(literacy_rate.head())

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525
         Country       GDP
0  United States  30500000
1          China  19230000
2          India   4187000
3          Japan   4180000
4        Germany   4744000
         country  internet_users
0  United States       312000000
1          China      1080000000
2          India       850000000
3          Japan       118000000
4        Germany        79000000
            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

# **PART B**

Part B – Data Understanding
Task 5
Explore each dataset.
Find the following:
● Number of rows
● Number of columns
● Column names
● Data types
● Missing values
● Duplicate records

In [16]:
print("Population Dataset")

Population Dataset

In [17]:
print("Rows and Columns:")
print(population.shape)

Rows and Columns:
(25, 2)

In [18]:
print("Column Names:")
print(population.columns)

Column Names:
Index(['country', 'population'], dtype='object')

In [19]:
print("Data Types:")
print(population.dtypes)

Data Types:
country       object
population     int64
dtype: object

In [20]:
print("Missing Values:")
print(population.isnull().sum())

Missing Values:
country       0
population    0
dtype: int64

In [21]:
print("Duplicate Records:")
print(population.duplicated().sum())

Duplicate Records:
0

## PART C

Part C – Data Transformation
Task 6
Rename columns wherever necessary so that all datasets have a common column
name for merging.    Hint:
● Example: Country → country

In [22]:
population.rename(columns={'Country':'country'}, inplace=True)

population.columns

Index(['country', 'population'], dtype='object')

In [23]:
gdp.rename(columns={'Country':'country'}, inplace=True)

gdp.columns

Index(['country', 'GDP'], dtype='object')

In [24]:
internet_users.rename(columns={'Country':'country'}, inplace=True)

internet_users.columns

Index(['country', 'internet_users'], dtype='object')

In [25]:
literacy_rate.rename(columns={'Country':'country'}, inplace=True)

literacy_rate.columns

Index(['name', 'literacy_rate'], dtype='object')

Task 7
Convert the required columns into appropriate numeric data types.

In [26]:
population.dtypes

country       object
population     int64
dtype: object

In [27]:
population['population'] = pd.to_numeric(population['population'], errors='coerce')

In [28]:
gdp.dtypes

country    object
GDP         int64
dtype: object

In [31]:
gdp['GDP'] = pd.to_numeric(gdp['GDP'], errors='coerce')

In [32]:
internet_users.dtypes

country           object
internet_users     int64
dtype: object

In [33]:
internet_users['internet_users'] = pd.to_numeric(internet_users['internet_users'], errors='coerce')

In [34]:
literacy_rate.dtypes

name              object
literacy_rate    float64
dtype: object

Task 8
Merge all four datasets into one DataFrame.
Hint:
● Use the common column (country)
● Choose an appropriate join method.

In [35]:
merged_data = population.merge(gdp, on='country', how='outer')

merged_data.head()

     country  population       GDP
0  Argentina    45195774    640000
1  Australia    25687041   1880000
2     Brazil   212559417   2330000
3     Canada    38005238   2250000
4      China  1411778724  19230000

In [36]:
merged_data = merged_data.merge(internet_users, on='country', how='outer')

merged_data.head()

     country  population       GDP  internet_users
0  Argentina    45195774    640000        41000000
1  Australia    25687041   1880000        24000000
2     Brazil   212559417   2330000       181000000
3     Canada    38005238   2250000        36000000
4      China  1411778724  19230000      1080000000

In [38]:
literacy_rate.rename(columns={'name':'country'}, inplace=True)
merged_data = merged_data.merge(literacy_rate, on='country', how='outer')

merged_data.head()

     country  population       GDP  internet_users  literacy_rate
0  Argentina    45195774    640000        41000000           99.1
1  Australia    25687041   1880000        24000000           99.0
2     Brazil   212559417   2330000       181000000           93.2
3     Canada    38005238   2250000        36000000           99.0
4      China  1411778724  19230000      1080000000           97.2

In [39]:
merged_data.shape

(25, 5)

In [40]:
merged_data.columns

Index(['country', 'population', 'GDP', 'internet_users', 'literacy_rate'], dtype='object')

Task 9
Create the following calculated columns:
1. Internet Penetration (%)
2. GDP Per Capita
Hint:
Round the calculated values to two decimal places.

In [42]:
merged_data['Internet Penetration (%)'] = (
    merged_data['internet_users'] / merged_data['population']
) * 100

merged_data['Internet Penetration (%)'] = merged_data['Internet Penetration (%)'].round(2)
merged_data[['country','Internet Penetration (%)']].head()

     country  Internet Penetration (%)
0  Argentina                     90.72
1  Australia                     93.43
2     Brazil                     85.15
3     Canada                     94.72
4      China                     76.50

In [44]:
merged_data['GDP Per Capita'] = (
    merged_data['GDP'] / merged_data['population']
)

merged_data['GDP Per Capita'] = merged_data['GDP Per Capita'].round(2)

In [46]:
merged_data[['country','GDP Per Capita']].head()

     country  GDP Per Capita
0  Argentina            0.01
1  Australia            0.07
2     Brazil            0.01
3     Canada            0.06
4      China            0.01

In [47]:
merged_data.head()

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,Argentina,45195774,640000,41000000,99.1,90.72,0.01
1,Australia,25687041,1880000,24000000,99.0,93.43,0.07
2,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
3,Canada,38005238,2250000,36000000,99.0,94.72,0.06
4,China,1411778724,19230000,1080000000,97.2,76.50,0.01

**Part D – Load Data
Task 10
Create a SQLite database. Store the final merged dataset into a table named
‘country_statistics’
Hint:
● Use the sqlite3 library.
● Load the DataFrame using pandas.**

In [48]:
import sqlite3

In [49]:
connection = sqlite3.connect("country_statistics.db")

In [50]:
merged_data.to_sql(
    'country_statistics',
    connection,
    if_exists='replace',
    index=False
)

25

In [51]:
import pandas as pd

pd.read_sql(
    "SELECT * FROM country_statistics",
    connection
)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,Argentina,45195774,640000,41000000,99.1,90.72,0.01
1,Australia,25687041,1880000,24000000,99.0,93.43,0.07
2,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
3,Canada,38005238,2250000,36000000,99.0,94.72,0.06
4,China,1411778724,19230000,1080000000,97.2,76.50,0.01
5,France,65273511,3211000,62000000,99.0,94.98,0.05
6,Germany,83240525,4744000,79000000,99.0,94.91,0.06
7,India,1380004385,4187000,850000000,77.7,61.59,0.00
8,Indonesia,273523615,1500000,212000000,96.0,77.51,0.01
9,Italy,60461826,2420000,56000000,99.0,92.62,0.04
10,Japan,125836021,4180000,118000000,99.0,93.77,0.03
11,Mexico,128932753,1810000,102000000,95.4,79.11,0.01
12,Netherlands,17441139,1150000,17000000,99.0,97.47,0.07
13,Norway,5421241,580000,5300000,100.0,97.76,0.11
14,Russia,145934462,2200000,125000000,99.7,85.65,0.02
15,Saudi Arabia,34813871,1100000,34000000,97.3,97.66,0.03
16,Singapore,5850342,530000,5600000,97.5,95.72,0.09
17,South Africa,59308690,410000,43000000,95.0,72.50,0.01
18,South Korea,51780579,1800000,50000000,98.8,96.56,0.03
19,Spain,46754778,1710000,44000000,98.6,94.11,0.04
20,Sweden,10353442,650000,10100000,99.0,97.55,0.06
21,Switzerland,8654622,940000,8500000,99.0,98.21,0.11
22,Turkey,84339067,1350000,69000000,96.7,81.81,0.02
23,United Kingdom,67886011,3839000,66000000,99.0,97.22,0.06
24,United States,331002651,30500000,312000000,99.0,94.26,0.09

Task 11
Verify that the data has been loaded successfully.
Hint:
Retrieve the first five records from the SQLite table.

In [52]:
pd.read_sql(
    "SELECT * FROM country_statistics LIMIT 5",
    connection
)

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,Argentina,45195774,640000,41000000,99.1,90.72,0.01
1,Australia,25687041,1880000,24000000,99.0,93.43,0.07
2,Brazil,212559417,2330000,181000000,93.2,85.15,0.01
3,Canada,38005238,2250000,36000000,99.0,94.72,0.06
4,China,1411778724,19230000,1080000000,97.2,76.50,0.01

In [ ]:
Part E – Data Analysis Using Pandas
Answer the following questions using pandas.
1 List the Top 5 countries by GDP.
2 List the Top 5 countries by population.
3 Calculate the average literacy rate.
4 List all countries having a literacy rate greater than 90%.
5 List all countries having an internet penetration greater than 70%.
6 List the Top 5 countries by GDP per capita.
7 Calculate the total population represented in the dataset.
8 Calculate the average internet penetration across all countries.
9 Identify the country having the highest number of internet users.
10 Find the correlation between Literacy Rate and Internet Penetration.       Hint:
Use the appropriate pandas statistical function.

In [54]:
merged_data.nlargest(5, 'GDP')[['country','GDP']]

          country       GDP
24  United States  30500000
4           China  19230000
6         Germany   4744000
7           India   4187000
10          Japan   4180000

In [55]:
merged_data.nlargest(5, 'population')[['country','population']]

          country  population
4           China  1411778724
7           India  1380004385
24  United States   331002651
8       Indonesia   273523615
2          Brazil   212559417

In [56]:
merged_data['literacy_rate'].mean()

np.float64(97.24799999999999)

In [57]:
merged_data[merged_data['literacy_rate'] > 90][['country','literacy_rate']]

           country  literacy_rate
0        Argentina           99.1
1        Australia           99.0
2           Brazil           93.2
3           Canada           99.0
4            China           97.2
5           France           99.0
6          Germany           99.0
8        Indonesia           96.0
9            Italy           99.0
10           Japan           99.0
11          Mexico           95.4
12     Netherlands           99.0
13          Norway          100.0
14          Russia           99.7
15    Saudi Arabia           97.3
16       Singapore           97.5
17    South Africa           95.0
18     South Korea           98.8
19           Spain           98.6
20          Sweden           99.0
21     Switzerland           99.0
22          Turkey           96.7
23  United Kingdom           99.0
24   United States           99.0

In [58]:
merged_data[merged_data['Internet Penetration (%)'] > 70][['country','Internet Penetration (%)']]

           country  Internet Penetration (%)
0        Argentina                     90.72
1        Australia                     93.43
2           Brazil                     85.15
3           Canada                     94.72
4            China                     76.50
5           France                     94.98
6          Germany                     94.91
8        Indonesia                     77.51
9            Italy                     92.62
10           Japan                     93.77
11          Mexico                     79.11
12     Netherlands                     97.47
13          Norway                     97.76
14          Russia                     85.65
15    Saudi Arabia                     97.66
16       Singapore                     95.72
17    South Africa                     72.50
18     South Korea                     96.56
19           Spain                     94.11
20          Sweden                     97.55
21     Switzerland                     98.21
22          Turkey                     81.81
23  United Kingdom                     97.22
24   United States                     94.26

In [59]:
merged_data.nlargest(5, 'GDP Per Capita')[['country','GDP Per Capita']]

          country  GDP Per Capita
13         Norway            0.11
21    Switzerland            0.11
16      Singapore            0.09
24  United States            0.09
1       Australia            0.07

In [60]:
merged_data['population'].sum()

np.int64(4720039725)

In [61]:
merged_data['Internet Penetration (%)'].mean()

np.float64(89.65960000000001)

In [62]:
merged_data.nlargest(1, 'internet_users')[['country','internet_users']]

  country  internet_users
4   China      1080000000

In [63]:
merged_data['literacy_rate'].corr(
    merged_data['Internet Penetration (%)']
)

np.float64(0.7727975681398502)

Part F – Data Analysis Using SQL
Answer the following questions using SQLite queries.
11 Display the Top 5 countries by GDP.
12 Find the average literacy rate.
13 Display all countries having literacy rate above 90%.
14 Find the Top 5 countries with the highest internet penetration.
15 Calculate the total population.
16 Find the country with the highest GDP per capita.  
17 Export the final merged dataset as a CSV file.  
18 Sort the dataset in descending order of GDP per Capita and display the Top 10
countries.
Write a short summary (5–6 points) explaining your ETL process, including:
● Data sources used
● Data cleaning steps
● Transformations performed
● Database loading process
● Key insights obtained from the analysis

In [64]:
pd.read_sql("""
SELECT country, gdp
FROM country_statistics
ORDER BY gdp DESC
LIMIT 5;
""", connection)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [65]:
pd.read_sql("""
SELECT AVG(literacy_rate) AS average_literacy_rate
FROM country_statistics;
""", connection)

   average_literacy_rate
0                 97.248

In [66]:
pd.read_sql("""
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90;
""", connection)

           country  literacy_rate
0        Argentina           99.1
1        Australia           99.0
2           Brazil           93.2
3           Canada           99.0
4            China           97.2
5           France           99.0
6          Germany           99.0
7        Indonesia           96.0
8            Italy           99.0
9            Japan           99.0
10          Mexico           95.4
11     Netherlands           99.0
12          Norway          100.0
13          Russia           99.7
14    Saudi Arabia           97.3
15       Singapore           97.5
16    South Africa           95.0
17     South Korea           98.8
18           Spain           98.6
19          Sweden           99.0
20     Switzerland           99.0
21          Turkey           96.7
22  United Kingdom           99.0
23   United States           99.0

In [67]:
pd.read_sql("""
SELECT country, `Internet Penetration (%)`
FROM country_statistics
ORDER BY `Internet Penetration (%)` DESC
LIMIT 5;
""", connection)

        country  Internet Penetration (%)
0   Switzerland                     98.21
1        Norway                     97.76
2  Saudi Arabia                     97.66
3        Sweden                     97.55
4   Netherlands                     97.47

In [68]:
pd.read_sql("""
SELECT SUM(population) AS total_population
FROM country_statistics;
""", connection)

   total_population
0        4720039725

In [69]:
pd.read_sql("""
SELECT country, `GDP Per Capita`
FROM country_statistics
ORDER BY `GDP Per Capita` DESC
LIMIT 1;
""", connection)

  country  GDP Per Capita
0  Norway            0.11

In [70]:
merged_data.to_csv("final_country_statistics.csv", index=False)

In [71]:
pd.read_sql("""
SELECT country, `GDP Per Capita`
FROM country_statistics
ORDER BY `GDP Per Capita` DESC
LIMIT 10;
""", connection)

          country  GDP Per Capita
0          Norway            0.11
1     Switzerland            0.11
2       Singapore            0.09
3   United States            0.09
4       Australia            0.07
5     Netherlands            0.07
6          Canada            0.06
7         Germany            0.06
8          Sweden            0.06
9  United Kingdom            0.06

# **dataAcquisitionCasestudy**
# **completed**



dataAcquisitionCasestudy